### ISSUE TITLE
add maximize minimize close icons

### ISSUE THREAD

**Issue by NoHckz** [RemyIsCool/userChrome.css#10]
its a really god theme but its hard to use in windows as it doesnt has the buttons ik linux already has a feature like that but it would be appreciated

**Comment by khannurien** [comment]
Quick hack in `userChrome.css` to get the window buttons back:

```css
#alltabs-button,
#page-action-buttons,
#tracking-protection-icon-container,
#identity-box {
	display: none;
}
.titlebar-buttonbox-container {
	position: absolute;
	top: 0;
	right: 0;

	opacity: 0.1;
	transition: 0.2s opacity ease;
}
.titlebar-buttonbox-container:hover {
	opacity: 1;
}
```

I am now looking for a way to shrink the tabs bar a bit from the right to avoid buttons overlapping on the tabs.
